### ISSUE TITLE
when will the software be pubilc ? 

### ISSUE THREAD

**Issue by zhoudreames** [AntonBankevich/LJA#1]
Hi，Anton Bankevich
I am very interested in your development assembly software，but i am waitting for  it so long,i dont know when will this software be public.

**Comment by AntonBankevich** [comment]
Hi, thank you for your interest and sorry for the delay. Making genome assembly work in practice is a very time-consuming work even after all the algorithms are designed. We have finally reached the first milestone and release the first version of LJA.
